"""002_remove_some_columns

Revision ID: 36853d79a06f
Revises: 0998c3b7903c
Create Date: 2026-08-15 18:10:35.136090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36853d79a06f'
down_revision: Union[str, Sequence[str], None] = '0998c3b7903c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'method')
    op.drop_column('requests', 'status_code')
    op.drop_column('requests', 'response_time_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('response_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('requests', sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
