"""003_add_new_columns_method_and_stuff

Revision ID: 60a4e22d0a64
Revises: 36853d79a06f
Create Date: 2026-08-16 08:59:04.901625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a4e22d0a64'
down_revision: Union[str, Sequence[str], None] = '36853d79a06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('method', sa.String(), server_default='GET', nullable=False))
    op.add_column('requests', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('requests', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'error')
    op.drop_column('requests', 'response_time')
    op.drop_column('requests', 'status_code')
    op.drop_column('requests', 'method')
    # ### end Alembic commands ###
